-- Create tables for PlanKeeper

CREATE TABLE IF NOT EXISTS plans (
  id SERIAL PRIMARY KEY,
  title VARCHAR(200),
  creation_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS todos (
  id SERIAL PRIMARY KEY,
  plan_id INTEGER NOT NULL REFERENCES plans(id) ON DELETE CASCADE,
  text TEXT NOT NULL,
  done BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS notes (
  id SERIAL PRIMARY KEY,
  plan_id INTEGER NOT NULL REFERENCES plans(id) ON DELETE CASCADE,
  text TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_plans_creation_date ON plans(creation_date DESC);
CREATE INDEX IF NOT EXISTS idx_todos_plan_id ON todos(plan_id);
CREATE INDEX IF NOT EXISTS idx_notes_plan_id ON notes(plan_id);
